@host = localhost
@port = 7071

### Trigger the *evaluate_kid_friendliness* function with query parameter

GET http://{{host}}:{{port}}/api/evaluate_kid_friendliness?location=Jackson+Heights,+Queens,+NY

### Trigger the *evaluate_kid_friendliness* function with JSON body

POST http://{{host}}:{{port}}/api/evaluate_kid_friendliness

{
    "location": "downtown Oklahoma City"
}
